<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Learn - </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- css bootstrap -->
        <link rel="stylesheet" type="text/css" href="../../../Public/www/Views/vendor/bootstrap/css/bootstrap.min.css">
        <!-- font-awesome -->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- css perso -->
        <link rel="stylesheet" type="text/css" href="../../../Public/www/Views/vendor/css/myStyle.css">
        <!-- fonts google -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Comfortaa|Lato:300">

        <!-- favicon -->
        <link rel="shortcut icon" href="./assets/img/favicon/favicon.ico" type="image/x-icon">
        <link rel="icon" href="./assets/img/favicon/favicon.png" type="image/png">
        <link rel="icon" sizes="32x32" href="./assets/img/favicon/favicon-32.png" type="image/png">
        <link rel="icon" sizes="64x64" href="./assets/img/favicon/favicon-64.png" type="image/png">
        <link rel="icon" sizes="96x96" href="./assets/img/favicon/favicon-96.png" type="image/png">
        <link rel="icon" sizes="196x196" href="./assets/img/favicon/favicon-196.png" type="image/png">
        <link rel="apple-touch-icon" sizes="152x152" href="./assets/img/favicon/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="60x60" href="./assets/img/favicon/apple-touch-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/favicon/apple-touch-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="./assets/img/favicon/apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="./assets/img/favicon/apple-touch-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="./assets/img/favicon/apple-touch-icon-144x144.png">
        <meta name="msapplication-TileImage" content="favicon-144.png">
        <meta name="msapplication-TileColor" content="#FFFFFF">

        <!-- style pour éviter d'avoir un problème avec la navbar -->
        <style>body { padding-top: 50px; padding-bottom: 20px; }</style>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <main>
            <!-- script phtml ici... -->
            <?php include '../../../App/Zyrass/Controllers/' . $template . '.phtml'; ?>
        </main>
        <!-- script jquery-->
        <script src="../../../Public/www/Views/vendor/js/jquery-3.2.1.min.js"></script>
        <!-- script bootstrap -->
        <script src="../../../Public/www/Views/vendor/bootstrap/js/bootstrap.min.js"></script>
        <!-- script perso -->
        <script src="../../../Public/www/Views/vendor/js/myScript.js"></script>
    </body>
</html>